"""Add job_listings.source (which platform a job came from) and a surrogate `id` identity column,
ahead of ingesting Ashby/Greenhouse/Lever jobs alongside the existing YC scrape.

Why this can't just be `Base.metadata.create_all(engine)`: see 0001's docstring -- this repo has
no migration framework backing its declarative models, so altering an existing table's columns
always needs an explicit ALTER TABLE here.

This is step 1 of an expand -> dual-write -> cutover -> contract sequence, not a one-shot switch.
`job_id` (the existing INTEGER primary key, YC's native numeric id) is left completely untouched --
still the primary key, still NOT NULL -- and `source_job_id`/`source` are added **nullable**, not
NOT NULL, even though every pre-existing row gets backfilled with a real value. That's deliberate:
JobDataServer and WebScraper deploy independently on Railway and never run migrations themselves
(only this repo's api/app.py lifespan does, on its own boot), so there's a real window after this
migration lands where WebScraper is still running its old INSERT statement, which knows nothing
about source_job_id/source and would violate a NOT NULL constraint on every single scrape. Leaving
them nullable here means that old code keeps working unmodified through the whole rollout; a later
contract migration tightens both columns to NOT NULL once every writer has been redeployed to set
them and `job_id` itself is dropped. (The unique constraint below is safe to add immediately
despite the nullability -- Postgres treats NULLs as distinct for uniqueness purposes, so it doesn't
reject today's NULL/NULL rows.)

Ashby and Lever job ids are UUID strings, and Greenhouse ids can exceed Postgres's 32-bit INTEGER
range and live in a separate id space from YC's -- `job_id` alone can no longer be a safe global
uniqueness key once those sources exist. `source_job_id` (TEXT, the source's native id, cast from
the existing integer job_id for pre-existing rows) plus `source`, unique together, replaces it.
`id` (BIGINT, Postgres IDENTITY) is the future primary key -- `ADD COLUMN ... GENERATED BY DEFAULT
AS IDENTITY` on an already-populated table auto-backfills every existing row via the new sequence,
same as any other identity column.
"""

from __future__ import annotations

from sqlalchemy import Connection, text

from shared.job_data import DEFAULT_JOB_SOURCE, load_job_table_name


def _column_exists(conn: Connection, table_name: str, column_name: str) -> bool:
	return (
		conn.execute(
			text(
				"""
				SELECT 1 FROM information_schema.columns
				WHERE table_name = :table_name AND column_name = :column_name
				"""
			),
			{"table_name": table_name, "column_name": column_name},
		).first()
		is not None
	)


def _constraint_exists(conn: Connection, table_name: str, constraint_name: str) -> bool:
	return (
		conn.execute(
			text(
				"""
				SELECT 1 FROM information_schema.table_constraints
				WHERE table_name = :table_name AND constraint_name = :constraint_name
				"""
			),
			{"table_name": table_name, "constraint_name": constraint_name},
		).first()
		is not None
	)


def apply(conn: Connection) -> None:
	table_name = load_job_table_name()

	if _column_exists(conn, table_name, "source_job_id"):
		print(f"{table_name!r}.source_job_id already exists; skipping column add + backfill.")
	else:
		print(f"Adding source_job_id TEXT and source TEXT columns to {table_name!r} (nullable for now)")
		conn.execute(text(f'ALTER TABLE "{table_name}" ADD COLUMN source_job_id TEXT'))
		conn.execute(text(f'ALTER TABLE "{table_name}" ADD COLUMN source TEXT'))

		print(f"Backfilling source_job_id/source for existing {table_name!r} rows as {DEFAULT_JOB_SOURCE!r}")
		conn.execute(
			text(
				f'UPDATE "{table_name}" SET source_job_id = job_id::text, source = :source '
				f"WHERE source_job_id IS NULL"
			),
			{"source": DEFAULT_JOB_SOURCE},
		)

	if _constraint_exists(conn, table_name, "uq_job_listings_source_source_job_id"):
		print(f"{table_name!r} already has the (source, source_job_id) unique constraint; skipping.")
	else:
		print(f"Adding UNIQUE (source, source_job_id) constraint on {table_name!r}")
		conn.execute(
			text(
				f'ALTER TABLE "{table_name}" '
				f"ADD CONSTRAINT uq_job_listings_source_source_job_id UNIQUE (source, source_job_id)"
			)
		)

	if _column_exists(conn, table_name, "id"):
		print(f"{table_name!r}.id already exists; skipping.")
	else:
		print(f"Adding surrogate id BIGINT identity column to {table_name!r} (future primary key)")
		conn.execute(text(f'ALTER TABLE "{table_name}" ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY'))

	if _constraint_exists(conn, table_name, "uq_job_listings_id"):
		print(f"{table_name!r} already has a unique constraint on id; skipping.")
	else:
		print(f"Adding UNIQUE (id) constraint on {table_name!r} (job_matches will FK onto this)")
		conn.execute(text(f'ALTER TABLE "{table_name}" ADD CONSTRAINT uq_job_listings_id UNIQUE (id)'))
